---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/dansong/scripts/ucle/inventory/hosts.yaml"
        group_file: "/home/dansong/scripts/ucle/inventory/groups.yaml"
        defaults_file: "/home/dansong/scripts/ucle/inventory/defaults.yaml"



runner:
    plugin: threaded
    options: 
        num_workers: 1

